apiVersion: apps/v1                 # API group for Deployments
kind: Deployment
metadata:
  name: proj2-app                   # Name of the Deployment object
  namespace: proj2-dev              # Target namespace (dev environment)
spec:
  replicas: 1                       # Single replica for dev (no scaling yet)
  selector:
    matchLabels:
      app: proj2-app                # Must match pod labels below
  template:                         # Pod template: defines how Pods are created
    metadata:
      labels:
        app: proj2-app              # Labels assigned to Pods (selected by Service)
    spec:
      containers:
        - name: app
          image: ghcr.io/bynflow/end-to-end-devops-pipeline:latest
          # NOTE: For local/dev convenience we use :latest.
          # In CD (Tekton) we will deploy immutable tags (e.g. short SHA) for reproducibility and rollback.
          ports:
            - containerPort: 5000   # Container port where the Flask app listens
          readinessProbe:           # When "ready", the Service can route traffic to this Pod
            httpGet:
              path: /health         # Health endpoint
              port: 5000
            initialDelaySeconds: 2  # Initial delay before the first probe
            periodSeconds: 5        # Probe interval
          livenessProbe:            # If failing, Kubernetes restarts the container
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
