apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: proj2-ci
spec:
  params:
    - name: url
      type: string
      description: Git repository URL to clone
    - name: revision
      type: string
      default: main
      description: Git revision (branch/tag/SHA)
  workspaces:
    - name: source
      description: Workspace where the repo will be cloned
  steps:
    - name: clone
      image: alpine/git:2.45.2
      workingDir: $(workspaces.source.path)
      command: ["sh", "-c"]
      args:
        - |
          set -eu

          echo "=== CLEAN WORKSPACE ==="
          # delete EVERYTHING inside workspace, including dotfiles
          find . -mindepth 1 -maxdepth 1 -exec rm -rf {} +

          git clone "$(params.url)" .
          git checkout "$(params.revision)"

          echo "=== DEBUG: repo root ==="
          ls -la
          echo "=== DEBUG: k8s/dev ==="
          ls -la k8s/dev
