apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-deployer-dev
  namespace: proj2-dev             # Grant permissions in the target env namespace
subjects:
  - kind: ServiceAccount
    name: tekton-deployer
    namespace: proj2-ci
roleRef:
  kind: ClusterRole
  name: edit                       # Built-in role: allows updating Deployments/Services/etc. in this namespace
  apiGroup: rbac.authorization.k8s.io
