apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: deploy-dev-run-
  namespace: proj2-ci
spec:
  taskRunTemplate:
    serviceAccountName: tekton-deployer
  pipelineRef:
    name: deploy-dev
  params:
    - name: repo_url
      value: https://github.com/bynflow/end-to-end-devops-pipeline.git
    - name: revision
      value: main
    - name: image
      value: ghcr.io/bynflow/end-to-end-devops-pipeline
    - name: tag
      value: f672db6   # e.g. 423d1d1 (must exist in GHCR)
  workspaces:
    - name: shared
      persistentVolumeClaim:
        claimName: proj2-shared-ws
