apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proj2-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/bynflow/end-to-end-devops-pipeline
    newTag: sha-f129adf
